--- 

- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Remove default site if exists
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create NGINX reverse proxy config file
  copy:
    dest: /etc/nginx/sites-available/reverse-proxy
    content: |
      server {
          listen 80;
          server_name _;

          location / {
              proxy_pass http://127.0.0.1:8080;
              proxy_http_version 1.1;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }

- name: Enable reverse proxy site
  file:
    src: /etc/nginx/sites-available/reverse-proxy
    dest: /etc/nginx/sites-enabled/reverse-proxy
    state: link
    force: true

- name: Test and reload NGINX
  shell: nginx -t && systemctl reload nginx
  args:
    executable: /bin/bash
