- name: Deploy GNS3 Server and File Browser
  hosts: gns3
  become: true

  vars:
    gns3_port: 3080
    filebrowser_port: 8080
    filebrowser_dir: /root/dossier_fileBrowser

  tasks:

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Enable universe and multiverse repositories
      shell: |
        add-apt-repository universe -y
        add-apt-repository multiverse -y
        add-apt-repository ppa:gns3/ppa -y
        apt update
      args:
        executable: /bin/bash

    - name: Install GNS3 server and dependencies
      apt:
        name:
          - gns3-server
          - qemu-system-x86
          - qemu-utils
          - qemu-kvm
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
          - python3-pip
          - wireshark
          - net-tools
        state: present
        update_cache: yes

    - name: Remove gns3-gui if installed
      apt:
        name: gns3-gui
        state: absent

    - name: Create GNS3 systemd service
      copy:
        dest: /etc/systemd/system/gns3server.service
        content: |
          [Unit]
          Description=GNS3 Server
          After=network.target

          [Service]
          Type=simple
          User=root
          WorkingDirectory=/root
          ExecStart=/usr/bin/gns3server --host 0.0.0.0 --port {{ gns3_port }}
          Restart=on-failure
          RestartSec=5s
          Environment=HOME=/root

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd
        - Enable and start GNS3

    - name: Create directory for File Browser
      file:
        path: "{{ filebrowser_dir }}"
        state: directory
        mode: '0755'

    - name: Create File Browser systemd service
      copy:
        dest: /etc/systemd/system/filebrowser.service
        content: |
          [Unit]
          Description=File Browser Web File Manager
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/filebrowser -r {{ filebrowser_dir }} -p {{ filebrowser_port }} --address 0.0.0.0
          Restart=always
          User=root
          WorkingDirectory=/root
          Environment=HOME=/root

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd
        - Enable and start File Browser

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Enable and start GNS3
      systemd:
        name: gns3server
        enabled: yes
        state: restarted

    - name: Enable and start File Browser
      systemd:
        name: filebrowser
        enabled: yes
        state: restarted
