---
- name: Deploy GNS3 Server and/or File Browser
  hosts: gns3
  become: true

  vars:
    gns3_port: 3080
    filebrowser_port: 8080
    filebrowser_dir: /root/dossier_fileBrowser

  roles:
    - { role: gns3, when: gns3_install | default(true) }
    - { role: filebrowser, when: filebrowser_install | default(true) }
